app = "zhorben-pamyataj-2b005ccc-bdee-4477-ac38-4843f96f5bc6"

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0

[env]
NODE_ENV = 'production'
DEPLOY_ID = '210e75b9-7618-4adb-9130-02facb13d1df'

[[vm]]
memory = "512mb"
cpu_kind = "shared"
cpus = 1
